"""Episode / scene data models."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

InteractionType = Literal["dialogue", "action", "thought", "reaction"]


class InteractionEntry(BaseModel):
    """One character's contribution to a single turn of a scene simulation."""

    turn: int
    character_id: str
    type: InteractionType
    content: str
    directed_at: str | None = None  # id of the character this is aimed at

    def render(self) -> str:
        """One-line human-readable form, as stored in `Scene.interaction_log`."""
        target = f" -> {self.directed_at}" if self.directed_at else ""
        return f"[{self.turn}] {self.character_id} ({self.type}{target}): {self.content}"


class StoryBeat(BaseModel):
    """An atomic plot point inside a scene."""

    description: str                # what must happen
    involved_character_ids: list[str] = Field(default_factory=list)
    location_id: str | None = None
    mood: str | None = None         # "tense", "comedic", ...


class Scene(BaseModel):
    """A scene within an episode, generated by the Director."""

    scene_number: int
    title: str
    location_id: str | None = None
    participating_character_ids: list[str]
    objective: str                  # what the scene should accomplish narratively
    beats: list[StoryBeat] = Field(default_factory=list)
    # Filled after Character Agent simulation:
    interaction_log: list[str] = Field(default_factory=list)
    # Filled after Writer Agent:
    prose: str = ""


class Episode(BaseModel):
    """One chapter / 회차. The author provides the storyline; the system fills the rest."""

    episode_number: int
    title: str = ""
    author_storyline: str           # the author's rough outline for this episode
    scenes: list[Scene] = Field(default_factory=list)  # populated by Director Agent
    final_text: str = ""            # assembled prose from all scenes
    summary: str = ""               # generated after completion for memory
    status: str = "queued"          # queued | in_progress | completed
    pacing: str = "normal"          # slow (introspective) | normal | fast (action-heavy)
